// Copyright 2024 anyone-Hub
// BuildService — live compiler output interception for warning collection.
//
// GUARDRAILS (v1.1.0):
// ✅ THREAD-SAFE  — ConcurrentLinkedQueue for multi-worker collection.
// ✅ LOCK-FREE    — zero blocking, zero synchronised blocks, zero await().
// ✅ READ-ONLY    — does not modify compiler behavior; only captures output.
// ✅ MULTI-PATTERN — 4 new warning categories caught via compiled Regex.

package com.anyonehub.diagnostics.service

import com.anyonehub.diagnostics.model.CompilerWarning
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.services.BuildService
import org.gradle.api.services.BuildServiceParameters
import org.gradle.tooling.events.FinishEvent
import org.gradle.tooling.events.OperationCompletionListener
import java.io.File
import java.util.concurrent.ConcurrentLinkedQueue

/**
 * A Gradle [BuildService] that collects all compiler warnings emitted to
 * stdout/stderr during `KotlinCompile` and `JavaCompile` task execution.
 *
 * ## v1.1.0 Changes
 * - Multi-pattern Regex engine inside [collectLine] catches 4 new categories.
 * - Stored as [CompilerWarning] with a [CompilerWarning.category] field that
 *   drives grouping in the HTML report generated by [AggregateProjectHealthReportTask].
 *
 * ## Thread Safety
 * Multiple compile tasks may run in parallel. [ConcurrentLinkedQueue] guarantees
 * lock-free thread-safe insertion from any Gradle worker thread.
 */
abstract class CompilerOutputCollectorService :
    BuildService<CompilerOutputCollectorService.Params>,
    OperationCompletionListener,
    AutoCloseable {

    interface Params : BuildServiceParameters {
        /**
         * Directory where the service writes `compiler-service-output.txt`.
         * Passed as a [DirectoryProperty] (lazy) — never resolved at configuration time.
         * DEFECT-4 fix: was previously Property<String>, which required an eager .get()
         * call in ProjectHealthPlugin to extract an absolute path string.
         */
        val outputDir: DirectoryProperty
    }

    /**
     * Thread-safe queue of parsed compiler warnings.
     * Populated by [collectLine] from parallel compile task listeners.
     */
    private val collectedWarnings = ConcurrentLinkedQueue<CompilerWarning>()

    // ─────────────────────────────────────────────────────────────────────────
    // Compiled Regex patterns — created once, reused across all threads.
    // All patterns compile at class-load time; no dynamic allocation in hot path.
    // ─────────────────────────────────────────────────────────────────────────

    /** Kotlin/Java `w: file:///...kt:line:col: '...' is deprecated. ...` */
    private val kotlinFileDeprecationRegex = Regex(
        """w:\s+(?:file:///)?(?:[A-Za-z]:)?([^:]+\.kt):(\d+):(\d+):\s+(.+deprecated.+)""",
        RegexOption.IGNORE_CASE
    )

    /**
     * Generic Kotlin `w:` prefix line that carries deprecation text but no file location.
     * Catches: `'class MasterKey : Any' is deprecated. Deprecated in Java.`
     *          `'fun rememberPaymentSheet(...): PaymentSheet' is deprecated.`
     */
    private val kotlinGenericDeprecationRegex = Regex(
        """w:\s+.+(?:deprecated|Deprecated in Java)\.""",
        RegexOption.IGNORE_CASE
    )

    /**
     * Kotlin 2.4 redundant compiler argument warning.
     * Catches: `w: The argument '-Xannotation-default-target=param-property' is redundant
     *               for the current language version 2.4.`
     *          `w: The argument '-Xcontext-parameters' is redundant ...`
     */
    private val kotlin24RedundancyRegex = Regex(
        """w:\s+The argument\s+'(-X[^']+)'\s+is redundant""",
        RegexOption.IGNORE_CASE
    )

    /**
     * ANTLR UNSAFE_CALL suppression warning.
     * Catches: `w: ... Suppression of error 'UNSAFE_CALL' might compile and work,
     *               but the compiler behavior is UNSPECIFIED`
     */
    private val antlrUnsafeCallRegex = Regex(
        """w:.*Suppression of error 'UNSAFE_CALL'""",
        RegexOption.IGNORE_CASE
    )

    /**
     * `javac` file-located deprecation warning.
     * Format: `/path/to/File.java:42: warning: [deprecation] method() in Class has been deprecated`
     */
    private val javaFileDeprecationRegex = Regex(
        """([^:\s][^:]*\.java):(\d+):\s+warning:\s+\[deprecation]\s+(.+)""",
        RegexOption.IGNORE_CASE
    )

    /**
     * `javac` generic deprecation (no file location).
     * Catches: `warning: [deprecation] ...` and `Note: ... uses deprecated API.`
     */
    private val javaGenericDeprecationRegex = Regex(
        """(?:warning:\s+\[deprecation]|Note:.*uses.*deprecated).*""",
        RegexOption.IGNORE_CASE
    )

    /**
     * `javac` unchecked cast warning.
     * Catches: `warning: [unchecked] unchecked cast`
     */
    private val javaUncheckedRegex = Regex(
        """warning:\s+\[unchecked]\s+.+""",
        RegexOption.IGNORE_CASE
    )

    // ─────────────────────────────────────────────────────────────────────────
    // Public API
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Called from `StandardOutputListener` / `StandardErrorListener` callbacks
     * on compile tasks. Classifies the line against all known patterns and, on
     * a match, enqueues a [CompilerWarning] with the correct [CompilerWarning.category].
     *
     * **Hot path — zero allocations on non-matching lines.**
     * The fast early-exit guards (`contains` checks) avoid regex evaluation on
     * the vast majority of compiler output lines.
     *
     * @param line    Raw compiler output line.
     * @param source  Language of the originating compile task: "Kotlin" or "Java".
     */
    fun collectLine(line: String, source: String) {
        val trimmed = line.trimEnd()
        if (trimmed.isEmpty()) return

        when (source) {
            "Kotlin" -> classifyKotlinLine(trimmed)
            "Java"   -> classifyJavaLine(trimmed)
        }
    }

    /** Returns the current count of collected warnings (for diagnostics). */
    fun warningCount(): Int = collectedWarnings.size

    /**
     * Legacy no-op — file writing is deferred to [close] to keep worker threads
     * fully unblocked during parallel compilation.
     */
    fun drainToFile(outputFile: File): Int = 0

    /** [OperationCompletionListener] — passively collects; no action needed here. */
    override fun onFinish(event: FinishEvent) = Unit

    /**
     * Flush the collected warnings to disk.
     * Called by Gradle after ALL tasks in the build finish — zero risk of
     * writing partial data while compile tasks are still running.
     */
    override fun close() {
        val outDir = parameters.outputDir.orNull?.asFile ?: return
        val outputFile = File(outDir, "compiler-service-output.txt")
        outputFile.parentFile?.mkdirs()
        val warnings = collectedWarnings.toList()
        if (warnings.isNotEmpty()) {
            outputFile.bufferedWriter().use { writer ->
                writer.appendLine(CompilerWarning.SECTION_HEADER)
                warnings.forEach { warning ->
                    writer.appendLine(warning.toIntermediateLine())
                }
                writer.appendLine(CompilerWarning.SECTION_FOOTER)
            }
        }
        collectedWarnings.clear()
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Private classification logic
    // ─────────────────────────────────────────────────────────────────────────

    private fun classifyKotlinLine(line: String) {
        // Fast guard: all Kotlin compiler warnings start with "w:"
        if (!line.startsWith("w:")) return

        // ── Priority 1: Kotlin 2.4 redundant argument ─────────────────────────
        if (line.contains("is redundant", ignoreCase = true)) {
            val match = kotlin24RedundancyRegex.find(line) ?: return
            enqueue(
                language = "Kotlin",
                sourceFile = "compiler-args",
                line = -1, column = -1,
                flag = "redundant-arg",
                snippet = "Redundant compiler argument: ${match.groupValues[1]}",
                category = CompilerWarning.CAT_KOTLIN_REDUNDANCIES,
            )
            return
        }

        // ── Priority 2: ANTLR UNSAFE_CALL suppression ─────────────────────────
        if (line.contains("UNSAFE_CALL", ignoreCase = true)) {
            if (antlrUnsafeCallRegex.containsMatchIn(line)) {
                enqueue(
                    language = "Kotlin",
                    sourceFile = extractFileFromWLine(line),
                    line = -1, column = -1,
                    flag = "UNSAFE_CALL",
                    snippet = line.removePrefix("w:").trim().take(120),
                    category = CompilerWarning.CAT_ANTLR_UNSAFE,
                )
                return
            }
        }

        // ── Priority 3: File-located deprecation ──────────────────────────────
        if (line.contains("deprecated", ignoreCase = true)) {
            val fileMatch = kotlinFileDeprecationRegex.find(line)
            if (fileMatch != null) {
                val message = fileMatch.groupValues[4]
                enqueue(
                    language = "Kotlin",
                    sourceFile = fileMatch.groupValues[1],
                    line = fileMatch.groupValues[2].toIntOrNull() ?: -1,
                    column = fileMatch.groupValues[3].toIntOrNull() ?: -1,
                    flag = "w: (deprecated)",
                    snippet = cleanDeprecationMessage(message),
                    category = CompilerWarning.CAT_DEPRECATIONS,
                )
                return
            }

            // ── Priority 4: Generic deprecation (no file, e.g. "Deprecated in Java.") ─
            if (kotlinGenericDeprecationRegex.containsMatchIn(line)) {
                enqueue(
                    language = "Kotlin",
                    sourceFile = "unknown",
                    line = -1, column = -1,
                    flag = "w: (deprecated)",
                    snippet = line.removePrefix("w:").trim().take(120),
                    category = CompilerWarning.CAT_DEPRECATIONS,
                )
            }
        }
    }

    private fun classifyJavaLine(line: String) {
        // ── File-located javac deprecation ────────────────────────────────────
        if (line.contains("[deprecation]", ignoreCase = true)) {
            val fileMatch = javaFileDeprecationRegex.find(line)
            if (fileMatch != null) {
                enqueue(
                    language = "Java",
                    sourceFile = fileMatch.groupValues[1],
                    line = fileMatch.groupValues[2].toIntOrNull() ?: -1,
                    column = -1,
                    flag = "[deprecation]",
                    snippet = fileMatch.groupValues[3].take(120),
                    category = CompilerWarning.CAT_JAVA_COMPILER,
                )
                return
            }
            // Generic without file location
            if (javaGenericDeprecationRegex.containsMatchIn(line)) {
                enqueue(
                    language = "Java",
                    sourceFile = "unknown",
                    line = -1, column = -1,
                    flag = "[deprecation]",
                    snippet = line.trim().take(120),
                    category = CompilerWarning.CAT_JAVA_COMPILER,
                )
                return
            }
        }

        // ── Unchecked cast ─────────────────────────────────────────────────────
        if (line.contains("[unchecked]", ignoreCase = true) &&
            javaUncheckedRegex.containsMatchIn(line)
        ) {
            enqueue(
                language = "Java",
                sourceFile = "unknown",
                line = -1, column = -1,
                flag = "[unchecked]",
                snippet = line.trim().take(120),
                category = CompilerWarning.CAT_JAVA_COMPILER,
            )
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Utility helpers
    // ─────────────────────────────────────────────────────────────────────────

    private fun enqueue(
        language: String,
        sourceFile: String,
        line: Int,
        column: Int,
        flag: String,
        snippet: String,
        category: String,
    ) {
        collectedWarnings.add(
            CompilerWarning(
                language = language,
                sourceFile = sourceFile,
                line = line,
                column = column,
                flag = flag,
                snippet = snippet.take(120),
                category = category,
            )
        )
    }

    /**
     * Attempts to extract a file path from a `w: file:///path/to/File.kt:...` line.
     * Returns "unknown" if no path can be identified.
     */
    private fun extractFileFromWLine(line: String): String {
        val filePathRegex = Regex("""(?:file:///)?([A-Za-z]?[^:]+\.kt):\d+""")
        return filePathRegex.find(line)?.groupValues?.get(1) ?: "unknown"
    }

    /**
     * Strips the `'X' is deprecated. Use Y instead.` boilerplate from a
     * deprecation message, returning just the API name and suggestion.
     */
    private fun cleanDeprecationMessage(message: String): String {
        val apiMatch = Regex("""'([^']+)'\s+is\s+deprecated\.?\s*(.{0,80})""")
            .find(message)
        return if (apiMatch != null) {
            val api = apiMatch.groupValues[1]
            val suggestion = apiMatch.groupValues[2].trim()
            if (suggestion.isNotEmpty()) "$api → $suggestion" else api
        } else {
            message.take(120)
        }
    }
}
